language: rust

rust:
  - nightly

cache: cargo

script:
  - cargo build
  - cargo test -- --nocapture
  - cargo doc && mv -r target/doc docs/api

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: docs
  keep-history: false
  on:
    branch: master
